### ISSUE TITLE
When run with cordova serve the browser hang

### ISSUE THREAD

**Issue by ido-ran** [mario-aleo/cordova-angular-angularMaterial-seed#1]
I've clone this repository and use cordova serve to run it in browser but chrome get hang and offer to kill the page after a while.
When I use cordova run ios it run find inside the iOS simulator.

Any ideas how to run it in chrome for quick development?

**Comment by mario-aleo** [comment]
Well, I use Brackets to web development, so I use "Brackets Server" and I never had a hard time using it to run the app on Google Chrome, i've never tried to run the server using cordova. I can take a look to find a way out for you, but I know that you can use a Node server or even the Visual Code Studio debbug to run the server in the localhost and have a quick development and debbug using Chrome.

**Comment by ido-ran** [comment]
Using Brackets it really works great, strange why cordova server cause Chrome to hang...

**Comment by mario-aleo** [comment]
Yeah, that was pretty strange, for now I didn't find a work around using cordova server, I'll keep looking.
Anyway, I'm happy that Brackets sounds like a good way for you. 
Also you (or anyone that whats to run on the app on Chrome) can use IIS Express or Node Server to create the localhost.

Well, if you feel like these options are the answer, you can close this issue, if not I'll keep my search and I'll answer down here. (For now, I'm just thinking that cordova server isn't supporting the frameworks because it's using a kind of outdate localhost server).

PS: I'm happy to have your issue to answer, makes me feel like these repository isn't being just used by me.

**Comment by carmona** [comment]
In my workflow, I use Gulp to build and bundle files, then serve them with the [gulp-webserver](https://www.npmjs.com/package/gulp-webserver) plugin (localhost with live reloading).

Now when it comes to testing cordova plugins, I have to `cordova run android` and test it on my physical device. Using the emulator should work but imho it's a waste of precious RAM since i have a device lying around.

@mario-aleo congrats on the initiative, i look forward to contribute to this project in any way I can!

**Comment by mario-aleo** [comment]
Thanks @carmona, I really appreciate your help.
